/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.matt_wise.flyover;

import org.testng.annotations.*;
import static org.testng.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
    }
}
