/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.matt_wise.flyover;


import javax.swing.*;
import java.awt.*;

public class App extends JFrame {


    public App() {
        initUI();
    }

    private void initUI() {

        add(new Board("/Users/matt/git/VoxelSpace/maps/C1W.png",
                "/Users/matt/git/VoxelSpace/maps/D1.png"));

        setSize(800, 600);

        setTitle("Application");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
    }

    public static void main(String[] args) {
        EventQueue.invokeLater(() -> {
            App ex = new App();
            ex.setVisible(true);
        });
    }
}
